<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Patient</name>
   <tag></tag>
   <elementGuidId>732a41dc-714c-4cc8-ae39-164bff1e88dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4ad68cd1-94d8-4962-aaad-e0c816d15aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>activeclassname</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>a138b3fd-aae3-41e1-bec1-bbb2d00a0b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>83d4d6b2-98bb-4fd7-86df-6ce498e3afc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link active</value>
      <webElementGuid>e3f2ce21-2f59-4bf2-b91a-3adfdc88836a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/patient</value>
      <webElementGuid>e437683d-16f3-4438-b474-df2e8522dbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patient</value>
      <webElementGuid>caab9557-172a-41ca-bb56-5965f5e0d5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;fluid&quot;]/div[@class=&quot;d-flex flex-column sidebar&quot;]/div[@class=&quot;mb-auto&quot;]/div[@class=&quot;pt-2&quot;]/a[@class=&quot;link active&quot;]</value>
      <webElementGuid>65432d0a-6afd-486c-9222-e782a0f8c071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/a[2]</value>
      <webElementGuid>2f7c23b5-5648-4063-a620-03904231fef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>00ec5e99-cb51-4220-9e4f-f2c1ec7598be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doctor'])[1]/preceding::a[1]</value>
      <webElementGuid>61263255-b55a-4091-a4d3-b279884ea0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/patient')]</value>
      <webElementGuid>b98fa3aa-c5c7-4f5f-9889-db37e76b52c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>f22612a1-1d34-4979-864a-8db4a86dddf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/patient' and (text() = 'Patient' or . = 'Patient')]</value>
      <webElementGuid>73cea551-fc9d-47c2-a491-efd4590eb682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
