<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Titik3</name>
   <tag></tag>
   <elementGuidId>4fa3301c-72a3-448f-a0b9-1d63763b3385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/main/div/div[3]/div[2]/div/div/div[2]/div[1]/div/div/div[3]/div[1]/div[1]/div[2]/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
