<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__provinceFamily</name>
   <tag></tag>
   <elementGuidId>4e1c5fea-ae7b-4d05-afa9-4c056d6d8b5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;provinceFamily&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='provinceFamily']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ed8be14-0630-4d95-8896-141310da02e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>provinceFamily</value>
      <webElementGuid>f55dd5d5-dbfd-42ac-a881-96748ed26721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7be49b5f-3654-4eaf-b31b-0a271411a0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-form-add-patient form-control</value>
      <webElementGuid>8c0376cb-8934-4b55-b555-bcd7e1e22fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;fluid&quot;]/main[1]/div[@class=&quot;form-patient-page&quot;]/div[@class=&quot;container&quot;]/form[1]/div[@class=&quot;row row-cols-md-2 row-cols-1&quot;]/div[@class=&quot;col&quot;]/input[@class=&quot;label-form-add-patient form-control&quot;]</value>
      <webElementGuid>141b1dd9-8d27-4ec8-9de7-0b940805a7ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='provinceFamily']</value>
      <webElementGuid>3996cac6-1bd1-443d-af20-826ef18423cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div[2]/form/div[11]/div[2]/input</value>
      <webElementGuid>2c1cdc11-3c0b-4d3e-989a-9b07b7e308e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/input</value>
      <webElementGuid>885b92d0-0df6-4322-b6ff-73bb4e76d2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'provinceFamily' and @type = 'text']</value>
      <webElementGuid>66069297-a76e-459e-a253-42343d560126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
