name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2.3
      with:
          version: '8.5.2'
          projectPath: '${{ github.workspace }}'
          args: 'katalonc -noSplash -runMode=console -projectPath="D:\Kuliah\semester 7\KATALON\Capstone Project\WEB-Automation\WEB-Automation.prj" -retry=0 -testSuitePath="Test Suites/All Test Suite/Edit Patient" -browserType="Chrome" -executionProfile="default" -apiKey="df19e081-8f5f-44bc-ad03-f4007d4ead58" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true'
